language: python
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35
  - python: 3.4
    env: TOXENV=py34
  - python: 3.3
    env: TOXENV=py33
  - python: 2.7
    env: TOXENV=py27
  - python: 2.6
    env: TOXENV=py26
install: pip install pytest pytest-pep8 pytest-cov
script: py.test -vv --pep8 --cov=bencode.py --cov-report=term-missing
